name: CI/CD Pipeline Without Docker

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Backend Tests
        run: |
          cd backend
          pytest

  frontend:
    name: Frontend Build & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Lint Frontend Code
        run: |
          cd frontend
          npm run lint

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  deploy:
    name: Deploy to Server (No Docker)
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Backend via SCP
        run: |
          scp -r backend ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/neuroflash/

      - name: Deploy Frontend via SCP
        run: |
          scp -r frontend ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/neuroflash/

      - name: SSH into Server and Restart Services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/neuroflash/backend
            pkill -f "uvicorn main:app" || true
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > backend.log 2>&1 &

            cd /home/${{ secrets.SERVER_USER }}/neuroflash/frontend
            pkill -f "npm start" || true
            nohup npm run start > frontend.log 2>&1 &
